sudo: required

services:
  - docker

notifications:
  email: rik.ribbers@gmail.com

script:
 - docker run rikribbers/erldev /bin/sh -c "cd /root; git clone https://github.com/rikribbers/foaas-erlang; cd foaas-erlang; make"
